version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    groups:
      dev-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "croniter"
          - "google-cloud-storage"
          - "pydantic"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
