changelog:
  categories:
    - title: Feat
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
        authors:
          - github-actions

    - title: Dependencies
      labels:
        - dependencies

    - title: Misc
      authors:
        - github-actions
