changelog:
  categories:
    - title: Feat
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - auto-update

    - title: Dependencies
      labels:
        - dependencies

    - title: Auto update
      labels:
        - auto-update
