# Used in GH workflows
# docker compose -f docker-compose.tests.yml run backuper_tests

services:
  postgres_15:
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=postgres

  postgres_14:
    image: postgres:14.6
    environment:
      - POSTGRES_PASSWORD=postgres

  postgres_13:
    image: postgres:13.8
    environment:
      - POSTGRES_PASSWORD=postgres

  postgres_12:
    image: postgres:12.12
    environment:
      - POSTGRES_PASSWORD=postgres

  postgres_11:
    image: postgres:11.16
    environment:
      - POSTGRES_PASSWORD=postgres

  mysql_57:
    image: mysql:5.7.42
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=database

  mysql_80:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=database

  mariadb_1011:
    restart: "unless-stopped"
    image: mariadb:10.11.2
    environment:
      - MARIADB_ROOT_PASSWORD=maria
      - MARIADB_DATABASE=maria

  mariadb_1006:
    restart: "unless-stopped"
    image: mariadb:10.6.12
    environment:
      - MARIADB_ROOT_PASSWORD=maria
      - MARIADB_DATABASE=maria

  mariadb_1005:
    restart: "unless-stopped"
    image: mariadb:10.5.19
    environment:
      - MARIADB_ROOT_PASSWORD=maria
      - MARIADB_DATABASE=maria

  mariadb_1004:
    restart: "unless-stopped"
    image: mariadb:10.4.28
    environment:
      - MARIADB_ROOT_PASSWORD=maria
      - MARIADB_DATABASE=maria

  backuper_tests:
    depends_on:
      - postgres_15
      - postgres_14
      - postgres_13
      - postgres_12
      - postgres_11
      - mysql_57
      - mysql_80
      - mariadb_1011
      - mariadb_1006
      - mariadb_1005
      - mariadb_1004
    build:
      context: ./
      dockerfile: Dockerfile
      target: tests
    environment:
      - DOCKER_TESTS=true
      - ZIP_ARCHIVE_PASSWORD=password