services:
  postgres_15:
    restart: "unless-stopped"
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 10015:5432

  postgres_14:
    restart: "unless-stopped"
    image: postgres:14.6
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 10014:5432

  postgres_13:
    restart: "unless-stopped"
    image: postgres:13.8
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 10013:5432

  postgres_12:
    restart: "unless-stopped"
    image: postgres:12.12
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 10012:5432

  postgres_11:
    restart: "unless-stopped"
    image: postgres:11.16
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 10011:5432

  mysql_57:
    restart: "unless-stopped"
    image: mysql:5.7.42
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=database
    ports:
      - 10057:3306

  mysql_80:
    restart: "unless-stopped"
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=database
    ports:
      - 10080:3306

  mariadb_1011:
    restart: "unless-stopped"
    image: mariadb:10.11.2
    environment:
      - MARIADB_ROOT_PASSWORD=mysql
      - MARIADB_DATABASE=database
    ports:
      - 11011:3808

  mariadb_1006:
    restart: "unless-stopped"
    image: mariadb:10.6.12
    environment:
      - MARIADB_ROOT_PASSWORD=mysql
      - MARIADB_DATABASE=database
    ports:
      - 11006:3808

  mariadb_1005:
    restart: "unless-stopped"
    image: mariadb:10.5.19
    environment:
      - MARIADB_ROOT_PASSWORD=mysql
      - MARIADB_DATABASE=database
    ports:
      - 11005:3808

  mariadb_1004:
    restart: "unless-stopped"
    image: mariadb:10.4.28
    environment:
      - MARIADB_ROOT_PASSWORD=mysql
      - MARIADB_DATABASE=database
    ports:
      - 11004:3808
