version: "3.4"

services:
  postgres_14:
    restart: "unless-stopped"
    image: postgres:14
    volumes:
      - pgdump_dev_postgresql_14:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 10014:5432
  postgres_13:
    restart: "unless-stopped"
    image: postgres:13
    volumes:
      - pgdump_dev_postgresql_13:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 10013:5432
  postgres_12:
    restart: "unless-stopped"
    image: postgres:12
    volumes:
      - pgdump_dev_postgresql_12:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 10012:5432
  postgres_11:
    restart: "unless-stopped"
    image: postgres:11
    volumes:
      - pgdump_dev_postgresql_11:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 10011:5432
  postgres_10:
    restart: "unless-stopped"
    image: postgres:10
    volumes:
      - pgdump_dev_postgresql_10:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 10010:5432
  pg_dump:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
volumes:
  pgdump_dev_postgresql_14:
  pgdump_dev_postgresql_13:
  pgdump_dev_postgresql_12:
  pgdump_dev_postgresql_11:
  pgdump_dev_postgresql_10: