site_name: backuper
theme:
  favicon: images/favicon.ico
  name: material
  palette:
    primary: purple

repo_name: rafsaf/backuper
repo_url: https://github.com/rafsaf/backuper

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables

nav:
  - Backuper: index.md
  - Upload providers:
      - providers/google_cloud_storage.md
      - providers/debug.md
  - Backup targets:
      - backup_targets/postgresql.md
      - backup_targets/mysql.md
      - backup_targets/mariadb.md
      - backup_targets/file.md
      - backup_targets/directory.md
  - Notifications:
      - notifications/discord.md
  - Deployment: deployment.md
  - Configuration: configuration.md
  - How to restore?: how_to_restore.md
  - Other:
      - other/history.md
      - other/development.md

plugins:
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: true

watch:
  - docs
  - mkdocs.yml

extra:
  version:
    provider: mike
