services:
  ogion_unit_tests:
    restart: "no"
    network_mode: "host"
    platform: linux/${OGION_ARCH}
    build:
      context: ./../
      dockerfile: docker/Dockerfile
      target: tests

  ogion_acceptance_tests:
    restart: "no"
    network_mode: "host"
    platform: linux/${OGION_ARCH:-amd64}
    build: 
      context: ./../
      dockerfile: docker/Dockerfile
      target: build
    command: python -m ogion.main --single
    env_file:
      - ./../.env
