services:
  ogion_tests_amd64:
    restart: "no"
    networks:
      - ogion
    platform: linux/amd64
    build:
      context: ./../
      dockerfile: docker/Dockerfile
      target: tests
    environment:
      - DOCKER_TESTS=true
      - ZIP_ARCHIVE_PASSWORD=password

  ogion_tests_arm64:
    restart: "no"
    networks:
      - ogion
    platform: linux/arm64
    build:
      context: ./../
      dockerfile: docker/Dockerfile
      target: tests
    environment:
      - DOCKER_TESTS=true
      - ZIP_ARCHIVE_PASSWORD=password

networks:
  ogion: