name: tests
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

jobs:
  tests:
    strategy:
      matrix:
        arch: ["amd64", "arm64"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/${{ matrix.arch }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Touch .env
        run: touch .env

      - name: Download and start db containers
        run: make docker_dbs_setup

      - name: Build image and run tests in container
        run: make tests_${{ matrix.arch }}
