name: Run pytest based tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build containers
        run: docker compose -f docker-compose.tests.yml build

      - name: Run tests in container
        run: docker compose -f docker-compose.tests.yml run pg_dump_tests
