name: tests
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

jobs:
  tests:
    strategy:
      matrix:
        arch: ["amd64", "arm64"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/${{ matrix.arch }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Download and start db containers
        run: docker compose up -d postgres_15 postgres_14 postgres_13 postgres_12 postgres_11 mysql_57 mysql_80 mariadb_1011 mariadb_1006 mariadb_1005 mariadb_1004

      - name: Build image and run tests in container
        run: docker compose run --rm --build backuper_tests_${{ matrix.arch }}
