name: Run pytest based tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download and start db containers
        run: docker compose -f docker-compose.tests.yml up -d postgres_15 postgres_14 postgres_13 postgres_12 postgres_11 mysql_57 mysql_80

      - name: Build image and run tests in container
        run: docker compose -f docker-compose.tests.yml run backuper_tests
